export const ADD_TODO = 'ADD_TODO';
export type ADD_TODO = typeof ADD_TODO;

export const UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS';
export type UPDATE_TODO_STATUS = typeof UPDATE_TODO_STATUS;

export const UPDATE_TODO_VISIBILITY = 'UPDATE_TODO_VISIBILITY';
export type UPDATE_TODO_VISIBILITY = typeof UPDATE_TODO_VISIBILITY;